# -*- mode: ruby -*-
# vi: set ft=ruby :

# Use Vagrant v.2 configutation
Vagrant.configure("2") do |config|

  # Using Ubuntu 16.04 LTS
  config.vm.box = "ubuntu/xenial64"

  # Mapping jobproxy port of the guest to the same port of the host
  config.vm.network "forwarded_port", guest: 9999, host: 9999

  # TODO Mount the target folder containing jar file into the VM
  config.vm.synced_folder "../JobProxyServerCLI/target", "/jobproxy", id: "target"
  config.vm.synced_folder ".", "/jobproxy_logs", id: "logs"

  # Provision to the shell, install the required software, add docker group  and run the jar.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    sudo apt-get update
    sudo apt-get install -y docker-engine
    sudo apt-get install -y openjdk-8-jre
    sudo groupadd docker
    sudo gpasswd -a ${USER} docker
    sudo service docker restart
    newgrp docker
    LOGFILE=/jobproxy_logs/jobproxy_test.log
    PIDFILE=/jobproxy_logs/jobproxy_test.pid
    JOBPROXY_OPTS="-f Local -d"
    nohup java -jar /jobproxy/JobProxyServerCLI-0.1.0.beta.1.7.jar $JOBPROXY_OPTS < /dev/null > $LOGFILE 2>&1 &
    echo $! > $PIDFILE
  SHELL
end
